services:

# *** CORE ********************************************************************

  clickhouse:
    image: "clickhouse/clickhouse-server:latest-alpine"
    restart: "always"
    volumes:
      - ./config/config.xml:/etc/clickhouse-server/config.xml
      - ./config/users.d:/etc/clickhouse-server/users.d
    ports:
      - "8123:8123"
      - "9000:9000"
    ulimits:
      nproc: 65535
      nofile:
        soft: 262144
        hard: 262144

