version: "3.9"

services:

  base:
    image: "minio/minio:RELEASE.2020-10-28T08-16-50Z"
    restart: "always"
    command: server --address=":9001" /data1
    environment:
      MINIO_ACCESS_KEY: accessKey
      MINIO_SECRET_KEY: secretKey
    volumes:
      - ./data1:/data1
    ports:
      - "9001:9001"
    
  tiny:
    image: "minio/minio:RELEASE.2020-10-28T08-16-50Z"
    restart: "always"
    command: server --address=":9002" /data2
    environment:
      MINIO_ACCESS_KEY: accessKey
      MINIO_SECRET_KEY: secretKey
      MINIO_COMPRESS: "on"
      MINIO_COMPRESS_EXTENSIONS: ""
      MINIO_COMPRESS_MIME_TYPES: ""
    volumes:
      - ./data2:/data2
    ports:
      - "9002:9002"
 
